import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css';
import '../lib/fontawesome'; 
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Add weights you need
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Hassan.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
     <html lang="en" className={poppins.className}>
      
      <body>
              <Header />
        {children}
        </body>
    </html>
    </>
  );
}
